services:
  projectmanagementfe:
    image: mv1212/projectmanagementfe:latest
    container_name: projectmanagementfe
    ports:
      - "3031:3031"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://backend.quangminhvu.id.vn/api/v1
      - NEXT_PUBLIC_SOCKET_URL=https://backend.quangminhvu.id.vn
      - PORT=3031
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
